[package]
name = "osmtools"
version = "0.1.0"
edition = "2021"

[dependencies]
osmpbfreader = "0.16.1"
rand = "0.8.5"
reqwest = { version = "0.12.9", features = ["blocking"]}
smartstring = "1.0.1"
tokio = "1.41.1"
